### ISSUE TITLE
Dockerfile is not included

### ISSUE THREAD

**Issue by joedborg** [OpenFOAM/OpenFOAM-3.0.x#2]
There is no repository that contains the Dockerfile and dependencies; I'd like to work on these.

**Comment by OpenFOAM** [comment]
We have not yet done anything with Docker.  If you develop a Dockerfile for OpenFOAM feel free to contribute it to the OpenFOAM Foundation for release with OpenFOAM.

**Comment by joedborg** [comment]
Then how have you creating and distributing the docker image? http://www.openfoam.com/download/install-binary.php

Is OpenFOAM.com separate?

**Comment by OpenFOAM** [comment]
OpenFOAM.com is owned by ESI who have chosen not to contribute to OpenFOAM development.
For details of  OpenFOAM development and release by the OpenFOAM Foundation see
http://cfd.direct/openfoam/about/
